### ISSUE TITLE
BA-19.7 Flugplan

### ISSUE THREAD

**Issue by nstuder** [hannesbraun/badenair#105]
- [ ] Die Mittarbeiter werden den Flügen zugeteilt
- [ ] Liegt eine Störung vor wird der Flugleiter Benachrichtigt
- [ ] Der Flugleiter kann darauf reagieren
- [ ] Der Flugplan wird in Echtzeit im Frontend angezeigt

**Comment by Tenetar** [comment]
finally works with all undefined features
