### ISSUE TITLE
Anstehende Flüge (Personal)

### ISSUE THREAD

**Issue by hannesbraun** [hannesbraun/badenair#145]
Laut Lastenheft (FA6.3.5) soll es möglich sein die anstehenden Flüge einzusehen. Das geht meines Wissens nach für den genau nächsten Flug zwar über die Start-/Landungs-Seite, nicht aber für mehrere Flüge. Der Punkt im Lastenheft ist aber formuliert als Mehrzahl.
Brauchen wir eine extra Seite oder etwas ähnliches um der Kabinencrew und den Piloten ihre anstehenden Flüge anzuzeigen? Oder wie handhaben wir das?

**Comment by nstuder** [comment]
@hannesbraun Ich finde eine neue Seite eigentlich ganz sinnvoll. Oder wir fügen diese Information noch in den Schichtplan/Breitschaftsdienstplan mit ein. #146
