### ISSUE TITLE
Urlaubsplanung Anpassen

### ISSUE THREAD

**Issue by nstuder** [hannesbraun/badenair#154]
* Nur bis zum 10. nöglich
* Urlaubstage auf 36 erhöhen
* Urlaub zählt von 0 Uhr bis 0 Uhr
* Zuweisung von Alternativpersonal bei Urlaub

**Comment by jstuerzel** [comment]
* Piloten können nur Urlaub nehmen solange in diesem Zeitraum noch kein anderer Pilot Urlaub hat
